#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_SCRIPT="${SCRIPT_DIR}/imds/build-execfuse.sh"
HOOKS="${SCRIPT_DIR}/imds/hooks"
TEST_ROOT="$(mktemp -d)"
MOUNTPOINT="${TEST_ROOT}/mount"
DAEMON_PID=""
PASS=0
FAIL=0

cleanup() {
  if mountpoint -q "$MOUNTPOINT"; then
    fusermount -u "$MOUNTPOINT" 2>/dev/null || umount -l "$MOUNTPOINT" 2>/dev/null || true
  fi
  if [[ -n "$DAEMON_PID" ]]; then
    kill "$DAEMON_PID" 2>/dev/null || true
    wait "$DAEMON_PID" 2>/dev/null || true
  fi
  rm -rf "$TEST_ROOT"
}
trap cleanup EXIT

pass() { echo "ok - $1"; PASS=$((PASS + 1)); }
fail() { echo "not ok - $1" >&2; FAIL=$((FAIL + 1)); }

for command in fusermount jq mountpoint runuser; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "SKIP: required command is unavailable: ${command}"
    exit 0
  }
done
[[ -c /dev/fuse ]] || {
  echo "SKIP: /dev/fuse is unavailable"
  exit 0
}
pkg-config --exists fuse 2>/dev/null || {
  echo "SKIP: libfuse development files are unavailable"
  exit 0
}

mkdir -p "${TEST_ROOT}/data" "$MOUNTPOINT"
mkdir -p "${TEST_ROOT}/lxc"
chmod 0755 "$TEST_ROOT" "${TEST_ROOT}/data" "$MOUNTPOINT"

cat >"${TEST_ROOT}/data/2100.json" <<'JSON'
{
  "cores": 4,
  "hostname": "fixture.thesaints.home",
  "mp0": "/host/private,mp=/private",
  "tags": "managed;profile-gpu-none"
}
JSON
: > "${TEST_ROOT}/lxc/2100.conf"

cat >"${TEST_ROOT}/pvesh" <<'MOCK'
#!/usr/bin/env bash
set -euo pipefail
[[ "$1" == get && "$3" == --output-format && "$4" == json ]]
if [[ "$2" == /nodes/localhost/lxc ]]; then
  find "$PVE_IMDS_TEST_DATA" -maxdepth 1 -type f -name '[1-9]*.json' -printf '%f\n' \
    | sed -n 's/^\([1-9][0-9]\{0,8\}\)\.json$/[{"vmid":\1}]/p' \
    | jq -s 'add // []'
  exit 0
fi
ctid="${2%/config}"
ctid="${ctid##*/}"
cat "${PVE_IMDS_TEST_DATA}/${ctid}.json"
MOCK
chmod +x "${TEST_ROOT}/pvesh"

"$BUILD_SCRIPT" "${TEST_ROOT}/execfuse" >/dev/null
PVE_IMDS_PVESH="${TEST_ROOT}/pvesh" \
PVE_IMDS_TEST_DATA="${TEST_ROOT}/data" \
PVE_IMDS_LOCAL_LXC_CONFIG_DIR="${TEST_ROOT}/lxc" \
  "${TEST_ROOT}/execfuse" "$HOOKS" "$MOUNTPOINT" \
    -f -oro,allow_other,default_permissions,fsname=pve-imds &
DAEMON_PID=$!

deadline=$((SECONDS + 10))
until mountpoint -q "$MOUNTPOINT"; do
  if ! kill -0 "$DAEMON_PID" 2>/dev/null || ((SECONDS >= deadline)); then
    echo "ERROR: execfuse did not mount ${MOUNTPOINT}" >&2
    exit 1
  fi
done

metadata="$(cat "${MOUNTPOINT}/2100/metadata.json")"
if jq -e '.cores == 4 and .hostname == "fixture.thesaints.home" and (has("mp0") | not)' \
  <<<"$metadata" >/dev/null; then
  pass "mounted metadata is generated and redacted"
else
  fail "mounted metadata is generated and redacted"
fi

expected_size="$(PVE_IMDS_PVESH="${TEST_ROOT}/pvesh" PVE_IMDS_TEST_DATA="${TEST_ROOT}/data" \
  "${SCRIPT_DIR}/imds/lib/pve-imds-generate" metadata 2100 | wc -c)"
actual_size="$(stat -c %s "${MOUNTPOINT}/2100/metadata.json")"
if [[ "$actual_size" == "$expected_size" ]]; then
  pass "getattr reports the exact generated byte size"
else
  fail "getattr reports the exact generated byte size"
fi

expected_slice="$(printf '%s' "$metadata" | dd bs=1 skip=3 count=12 status=none)"
actual_slice="$(dd if="${MOUNTPOINT}/2100/metadata.json" bs=1 skip=3 count=12 status=none)"
if [[ "$actual_slice" == "$expected_slice" ]]; then
  pass "offset reads return the expected snapshot slice"
else
  fail "offset reads return the expected snapshot slice"
fi

if printf 'changed' >"${MOUNTPOINT}/2100/metadata.json" 2>/dev/null; then
  fail "writes are rejected by the read-only mount"
else
  pass "writes are rejected by the read-only mount"
fi

cp "${TEST_ROOT}/data/2100.json" "${TEST_ROOT}/data/42.json"
: > "${TEST_ROOT}/lxc/42.conf"
if [[ "$(find "$MOUNTPOINT" -mindepth 1 -maxdepth 1 -printf '%f\n' | sort -n | paste -sd, -)" == '42,2100' ]]; then
  pass "root listing reflects newly owned CTs dynamically"
else
  fail "root listing reflects newly owned CTs dynamically"
fi

old_snapshot="$(cat "${MOUNTPOINT}/2100/metadata.json")"
exec {snapshot_fd}<"${MOUNTPOINT}/2100/metadata.json"
IFS= read -r -N 1 -u "$snapshot_fd" first_byte
cat >"${TEST_ROOT}/data/2100.json" <<'JSON'
{"cores":8,"hostname":"fixture.thesaints.home","tags":"profile-gpu-drm_intel"}
JSON
remaining="$(cat <&"$snapshot_fd")"
exec {snapshot_fd}<&-
if [[ "${first_byte}${remaining}" == "$old_snapshot" ]] \
  && jq -e '.cores == 8' "${MOUNTPOINT}/2100/metadata.json" >/dev/null; then
  pass "first read freezes one handle while a new handle sees changes"
else
  fail "first read freezes one handle while a new handle sees changes"
fi

concurrent_ok=true
declare -a reader_pids=()
for reader in 1 2 3 4 5 6 7 8; do
  cat "${MOUNTPOINT}/2100/metadata.json" >"${TEST_ROOT}/reader-${reader}.json" &
  reader_pids+=("$!")
done
for reader_pid in "${reader_pids[@]}"; do
  wait "$reader_pid" || concurrent_ok=false
done
for reader in 1 2 3 4 5 6 7 8; do
  jq -e '.cores == 8' "${TEST_ROOT}/reader-${reader}.json" >/dev/null || concurrent_ok=false
done
if [[ "$concurrent_ok" == true ]]; then
  pass "concurrent handles return complete independent JSON"
else
  fail "concurrent handles return complete independent JSON"
fi

if runuser -u nobody -- cat "${MOUNTPOINT}/2100/profiles.json" | jq -e '. == ["gpu-drm_intel"]' >/dev/null; then
  pass "an unprivileged host user can read through allow_other"
else
  fail "an unprivileged host user can read through allow_other"
fi

echo "${PASS} passed, ${FAIL} failed"
[[ "$FAIL" -eq 0 ]]